-- 创建线程文件相关脚本
CREATE TABLE IF NOT EXISTS THREAD_INFO (
  ID TEXT PRIMARY KEY,
  WORKSPACE TEXT,
  FILE_ID INTEGER,
  THREAD_ID TEXT,
  THREAD_NAME TEXT,
  DAEMON INTEGER,
  PRIO INTEGER,
  OS_PRIO INTEGER,
  TID TEXT,
  NID TEXT,
  ADDRESS TEXT,
  THREAD_STATUS INTEGER,
  TOP_METHOD TEXT,
  STACK_INFO TEXT
);
