-- 创建最近打开的文件相关脚本
CREATE TABLE IF NOT EXISTS FILE_WORKSPACE (
  ID TEXT PRIMARY KEY,
  FILE_PATH TEXT,
  CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FILE_INFO (
  ID TEXT PRIMARY KEY,
  WORKSPACE TEXT,
  FILE_PATH TEXT,
  FILE_TYPE INTEGER,
  EXE_TIME TIMESTAMP
);


