-- 创建CPU文件相关脚本
CREATE TABLE IF NOT EXISTS CPU_INFO (
  ID TEXT PRIMARY KEY,
  WORKSPACE TEXT,
  EXE_TIME TIMESTAMP,
  US REAL,
  SY REAL,
  IDS REAL,
  TASKS REAL,
  RUNNING REAL,
  SLEEPING REAL,
  MEM_TOTAL REAL,
  MEM_FREE REAL,
  MEM_USED REAL
);