[package]
name = "indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
common = {path = "../common"}

tantivy.workspace = true
regex.workspace = true
fxhash.workspace = true
once_cell.workspace=true